package ch.usi.inf.examples.synthetic_dp.common.api;

import ch.usi.inf.confidentialstorm.common.crypto.exception.EnclaveServiceException;
import ch.usi.inf.examples.synthetic_dp.common.api.model.SyntheticEncryptedRecord;

/**
 * Enclave-side service that encrypts synthetic records generated by the host spout.
 * Encryption (and routing AAD) happens inside the enclave; host only handles ciphertext.
 */
public interface SyntheticDataService {
    SyntheticEncryptedRecord encryptRecord(String key, String count, String userId) throws EnclaveServiceException;
}
